In [1]:
import pynwb

In [5]:
# Basics: https://pynwb.readthedocs.io/en/stable/tutorials/general/file.html#basics

In [1]:
import numpy as np
from pynwb import NWBFile, TimeSeries, NWBHDF5IO
from pynwb.epoch import TimeIntervals
from pynwb.file import Subject
from pynwb.behavior import SpatialSeries, Position
from datetime import datetime
from dateutil import tz

In [2]:
TimeSeries?

In [4]:
NWBFile?

In [3]:
session_start_time = datetime(2018, 4, 25, 2, 30, 3, tzinfo=tz.gettz("US/Pacific")) ## Time 0

nwbfile = NWBFile(
    session_description="Mouse exploring an open field",  # required
    identifier="Mouse5_Day3",  # required
    session_start_time=session_start_time,  # required
    session_id="session_1234",  # optional
    experimenter="My Name",  # optional
    lab="My Lab Name",  # optional
    institution="University of My Institution",  # optional
    related_publications="DOI:10.1016/j.neuron.2016.12.011",  # optional
)
print(nwbfile)

root pynwb.file.NWBFile at 0x140448677691984
Fields:
  experimenter: ['My Name']
  file_create_date: [datetime.datetime(2023, 1, 10, 16, 43, 50, 12839, tzinfo=tzlocal())]
  identifier: Mouse5_Day3
  institution: University of My Institution
  lab: My Lab Name
  related_publications: ['DOI:10.1016/j.neuron.2016.12.011']
  session_description: Mouse exploring an open field
  session_id: session_1234
  session_start_time: 2018-04-25 02:30:03-07:00
  timestamps_reference_time: 2018-04-25 02:30:03-07:00



In [4]:
##### Adding subject info 
nwbfile.subject = Subject(
    subject_id="001",
    age="P90D", # https://en.wikipedia.org/wiki/ISO_8601#Durations
    description="mouse 5",
    species="Mus musculus",
    sex="M",
)

In [8]:
#### Adding timeseries data 
data = list(range(100, 200, 10))
time_series_with_rate = TimeSeries(
    name="test_timeseries",
    data=data,
    unit="m",
    starting_time=0.0,
    rate=1.0, # hz 
)

In [9]:
time_series_with_rate

test_timeseries pynwb.base.TimeSeries at 0x140433887923984
Fields:
  comments: no comments
  conversion: 1.0
  data: [100 110 120 130 140 150 160 170 180 190]
  description: no description
  offset: 0.0
  rate: 1.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: m

In [10]:
### Irregularly sampled data 
timestamps = list(range(10))
time_series_with_timestamps = TimeSeries(
    name="test_timeseries",
    data=data,
    unit="m",
    timestamps=timestamps, # seconds 
)

In [15]:
### Add timeseries data to NWB file 
# TimeSeries objects can be added directly to NWBFile using:
# add_acquisition to add acquisition data (raw, acquired data that should never change),
# add_stimulus to add stimulus data, or
# add_stimulus_template to store stimulus templates.



In [16]:
nwbfile.add_acquisition(time_series_with_timestamps)

In [18]:
### Writing 

In [19]:
io = NWBHDF5IO("basics_tutorial.nwb", mode="w")
io.write(nwbfile)
io.close()

/Users/preeyakhanna/conda/envs/nwb37/lib/python3.7/site-packages/hdmf/build/objectmapper.py:260: DtypeConversionWarning: Spec 'TimeSeries/timestamps': Value with data type int64 is being converted to data type float64 as specified.
  warnings.warn(full_warning_msg, DtypeConversionWarning)


In [20]:
pwd

'/Users/preeyakhanna/bmi_dynamics_code/nwb_notebooks'

In [21]:
ls

basics_tutorial.nwb  tutorials.ipynb


In [26]:
with NWBHDF5IO("basics_tutorial.nwb", "r") as io:
    read_nwbfile = io.read()
    print(read_nwbfile.acquisition["test_timeseries"])
    print(read_nwbfile.acquisition["test_timeseries"].data[:])

test_timeseries pynwb.base.TimeSeries at 0x140433888525136
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (10,), type "<i8">
  description: no description
  interval: 1
  offset: 0.0
  resolution: -1.0
  timestamps: <HDF5 dataset "timestamps": shape (10,), type "<f8">
  timestamps_unit: seconds
  unit: m

[100 110 120 130 140 150 160 170 180 190]


In [28]:
with NWBHDF5IO("basics_tutorial.nwb", "r") as io:
    read_nwbfile = io.read()
    print(read_nwbfile.acquisition["test_timeseries"])
    print(read_nwbfile.acquisition["test_timeseries"].data[:2])

test_timeseries pynwb.base.TimeSeries at 0x140434433043408
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (10,), type "<i8">
  description: no description
  interval: 1
  offset: 0.0
  resolution: -1.0
  timestamps: <HDF5 dataset "timestamps": shape (10,), type "<f8">
  timestamps_unit: seconds
  unit: m

[100 110]


In [29]:
## Diff b/w spatial series and timeseries (can I use multi-d data for timeseries)

In [ ]:
#### Adding timeseries data 
data = list(range(100, 200, 10))
time_series_with_rate = TimeSeries(
    name="test_timeseries",
    data=data,
    unit="m",
    starting_time=0.0,
    rate=1.0, # hz 
)

In [31]:
data = np.array([[1, 2, 3], [4, 5, 6]])

In [32]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
time_series_with_rate = TimeSeries(
    name="test_timeseries",
    data=data,
    unit="spike counts",
    starting_time=0.0,
    rate=1.0, # hz 
)

In [38]:
time_series_with_rate

test_timeseries pynwb.base.TimeSeries at 0x140434968837584
Fields:
  comments: no comments
  conversion: 1.0
  data: [[1 2 3]
 [4 5 6]]
  description: no description
  offset: 0.0
  rate: 1.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: spike counts

In [52]:
nwbfile.add_trial_column?

In [5]:
# nwbfile.add_trial_column(
#     name="moveID",
#     description="which target condition is on",
#     data = np.array([10.1, 10.2])
# )
nwbfile.add_trial(start_time=1.0, stop_time=5.0)#, correct=True)
nwbfile.add_trial(start_time=6.0, stop_time=10.0)#, correct=False)

In [7]:
nwbfile.trials.to_dataframe()

start_time  stop_time
id                       
0          1.0        5.0
1          6.0       10.0

In [59]:
nwbfile.add_trial_column(
    name="moveID3",
    description="which target condition is on",
    #data = np.array([102.1, 102.2])
)

ValueError: column must have the same number of rows as 'id'

In [57]:
nwbfile.trials.colnames

('start_time', 'stop_time', 'correct', 'moveID', 'moveID2')

In [58]:
nwbfile.trials.to_dataframe()

start_time  stop_time  correct  moveID  moveID2
id                                                 
0          1.0        5.0     True    10.1    102.1
1          6.0       10.0    False    10.2    102.2

In [61]:
nwbfile.trials

trials pynwb.epoch.TimeIntervals at 0x140433888636560
Fields:
  colnames: ['start_time' 'stop_time' 'correct' 'moveID' 'moveID2']
  columns: (
    start_time <class 'hdmf.common.table.VectorData'>,
    stop_time <class 'hdmf.common.table.VectorData'>,
    correct <class 'hdmf.common.table.VectorData'>,
    moveID <class 'hdmf.common.table.VectorData'>,
    moveID2 <class 'hdmf.common.table.VectorData'>
  )
  description: experimental trials
  id: id <class 'hdmf.common.table.ElementIdentifiers'>