In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%matplotlib notebook

In [4]:
from online_analysis import generate_models

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


in task
in task
in task
Import Error in db.namelist: from tasklist import tasks -- likely error in a single task preventing import


Traceback (most recent call last):
  File "/Users/preeyakhanna/bmi3d/db/namelist.py", line 92, in <module>
    from bmilist import *
  File "/Users/preeyakhanna/bmi3d/config_files/bmilist.py", line 25, in <module>
    from ismore.ismore_bmi_lib import StateSpaceArmAssist, StateSpaceReHand, StateSpaceIsMore
ImportError: No module named ismore.ismore_bmi_lib
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pybasicbayes-0.2.4-py2.7-macosx-10.9-x86_64.egg/pybasicbayes/util/stats.py:11: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d



error importing BMI configuration variables


/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 21:43:10.405208. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [43]:
generate_models.model_individual_cell_tuning_curves(animal='grom', 
                                                   model_set_number=11, fit_intercept = False,
                                                   fit_task_spec_and_general = True, match_task_spec_n = True,
                                                   add_model_to_datafile = True)

online_analysis/generate_models.py:342: DeprecationWarning: openFile() is pending deprecation, use open_file() instead. You may use the pt2to3 tool to update your source code.
  h5file = tables.openFile(hdf_filename, mode="w", title=animal+'_tuning')



##############################
########## DAY 0 ##########
##############################
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 64, total trls in this blk 64
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 165, total trls in this blk 101
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 287, total trls in this blk 122
Staring shuff 0


online_analysis/generate_models.py:1191: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  A = np.mat(np.linalg.lstsq(x_hat[:-1, :], x_hat[1:, :])[0])



R2 again, 0.31
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
##############################
########## DAY 1 ##########
##############################
(64,) (64,) (51, 35) 6 (51,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (51, 35) 6 (51,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (51, 35) 6 (51,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 64, total trls in this blk 64
(129,) (129,) (21, 35) 6 (21,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(129,) (129,) (21, 35) 6 (21,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(129,) (129,) (21, 35) 6 (21,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 193, total trls in this blk 129
Staring shuff 0
R2 again, 0.37
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
No push
##############################
########## DAY 2 ##########
##############################
(64,) (64,) (24, 148) 6 (24,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (24, 148) 6 (24,)
[0. 1. 2. 3. 4. 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 23:43:18.198048. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [19]:
pdb

Automatic pdb calling has been turned ON


/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 21:54:35.877378. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [32]:
x=1

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 23:25:33.250011. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [33]:
from pylds.models import DefaultLDS


/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 23:41:43.825074. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [35]:
x = DefaultLDS(44, 20, 0)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 23:42:04.068567. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [42]:
x.sigma_obs.shape


(44, 44)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-07-08 23:42:28.900686. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)

