In [1]:
import os
os.chdir(os.environ['BMI_DYN'])
%load_ext autoreload
%autoreload 2
from online_analysis import co_obs_tuning_matrices

Import Error in db.namelist: from tasklist import tasks -- likely error in a single task preventing import
error importing BMI configuration variables


Traceback (most recent call last):
  File "/Users/preeyakhanna/bmi3d/db/namelist.py", line 92, in <module>
    from bmilist import *
  File "/Users/preeyakhanna/bmi3d/config_files/bmilist.py", line 25, in <module>
    from ismore.ismore_bmi_lib import StateSpaceArmAssist, StateSpaceReHand, StateSpaceIsMore
ImportError: No module named ismore.ismore_bmi_lib
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2021-03-22 16:54:31.756882. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [2]:
fname, bounds = co_obs_tuning_matrices.extract_radial_bin_edges_grom_jeev(make_last_bin_95th = True)

online_analysis/co_obs_tuning_matrices.py:1109: DeprecationWarning: openFile() is pending deprecation, use open_file() instead. You may use the pt2to3 tool to update your source code.
  hdf = tables.openFile(pref+hdf[hdfix:])



Task ix: 0
(9,) (9,) (40, 12) 6 (40,)
[0. 1. 2. 4. 5. 6. 7.]
# unique trials 9
Targ 0, N = 2
Targ 1, N = 1
Targ 2, N = 2
Targ 4, N = 1
Targ 5, N = 1
Targ 6, N = 1
Targ 7, N = 1
Task ix: 0
(116,) (116,) (29, 12) 6 (29,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 116
Targ 0, N = 19
Targ 1, N = 15
Targ 2, N = 14
Targ 3, N = 12
Targ 4, N = 13
Targ 5, N = 15
Targ 6, N = 12
Targ 7, N = 16
Task ix: 0
(84,) (84,) (42, 12) 6 (42,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 84
Targ 0, N = 12
Targ 1, N = 12
Targ 2, N = 7
Targ 3, N = 9
Targ 4, N = 11
Targ 5, N = 11
Targ 6, N = 10
Targ 7, N = 12
Task ix: 0
(73,) (73,) (38, 12) 6 (38,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 73
Targ 0, N = 11
Targ 1, N = 11
Targ 2, N = 8
Targ 3, N = 7
Targ 4, N = 6
Targ 5, N = 10
Targ 6, N = 10
Targ 7, N = 10
Mag size = 14172
Task ix: 0
(159,) (159,) (59, 13) 6 (59,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 159
Targ 0, N = 23
Targ 1, N = 18
Targ 2, N = 18
Targ 3, N = 21
Targ 4, N = 16
Targ 5, N = 23
Targ 6, N = 16


(63,) (63,) (18, 50) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 63
Targ 0, N = 7
Targ 1, N = 8
Targ 2, N = 8
Targ 3, N = 8
Targ 4, N = 8
Targ 5, N = 8
Targ 6, N = 8
Targ 7, N = 8
Task ix: 1
(29,) (29,) (31, 50) 6 (31,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 29
Targ 0, N = 4
Targ 1, N = 3
Targ 2, N = 4
Targ 3, N = 4
Targ 4, N = 3
Targ 5, N = 3
Targ 6, N = 4
Targ 7, N = 4
Task ix: 1
(64,) (64,) (47, 50) 6 (47,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 64
Targ 0, N = 8
Targ 1, N = 8
Targ 2, N = 8
Targ 3, N = 8
Targ 4, N = 8
Targ 5, N = 8
Targ 6, N = 8
Targ 7, N = 8
Mag size = 4536
Task ix: 0
(64,) (64,) (35, 48) 6 (35,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 64
Targ 0, N = 8
Targ 1, N = 8
Targ 2, N = 8
Targ 3, N = 8
Targ 4, N = 8
Targ 5, N = 8
Targ 6, N = 8
Targ 7, N = 8
Task ix: 1
(100,) (100,) (48, 48) 6 (48,)
[0. 1. 2. 3. 4. 5. 6. 7.]
# unique trials 100
Targ 0, N = 14
Targ 1, N = 13
Targ 2, N = 12
Targ 3, N = 12
Targ 4, N = 13
Targ 5, N = 12
Targ 6, N = 12
Targ 7, N = 12

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2021-03-22 16:54:37.911335. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [4]:
bounds

{('grom', 0): [0.8449011032036735,
  1.3217133113561907,
  1.858823194473303,
  3.222647503510716],
 ('grom', 1): [1.0035951015601758,
  1.6772566995699032,
  2.4269207690906507,
  3.9316321082294943],
 ('grom', 2): [1.7362123276285666,
  2.7169772583590954,
  3.7999810113822265,
  6.258933743582293],
 ('grom', 3): [0.5763165473963169,
  0.8761444449441645,
  1.217777077460449,
  1.9725359294058928],
 ('grom', 4): [0.5792701524255485,
  0.9105702829146649,
  1.307637640706114,
  2.128315619867405],
 ('grom', 5): [0.9312209577201052,
  1.4259929116248156,
  2.010989948708821,
  3.2691319252651887],
 ('grom', 6): [0.8333487318366937,
  1.2967712808002037,
  1.7927034602200997,
  2.948416252926167],
 ('grom', 7): [0.43639973021230666,
  0.6648901090224064,
  0.922748992497872,
  1.4741743345531173],
 ('grom', 8): [1.1009238772439203,
  1.7104131839580918,
  2.510727272827287,
  4.150952133687437],
 ('home', 0): [0.8893175214720093,
  1.4085160248692044,
  2.2928617294212916,
  5.894339348

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2021-03-22 16:57:07.743035. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [5]:
old_bounds = {('grom', 0): [0.8449011032036735,
  1.3217133113561907,
  1.858823194473303,
  3.222647503510716],
 ('grom', 1): [1.0035951015601758,
  1.6772566995699032,
  2.4269207690906507,
  3.9316321082294943],
 ('grom', 2): [1.7362123276285666,
  2.7169772583590954,
  3.7999810113822265,
  6.258933743582293],
 ('grom', 3): [0.5763165473963169,
  0.8761444449441645,
  1.217777077460449,
  1.9725359294058928],
 ('grom', 4): [0.5792701524255485,
  0.9105702829146649,
  1.307637640706114,
  2.128315619867405],
 ('grom', 5): [0.9312209577201052,
  1.4259929116248156,
  2.010989948708821,
  3.2691319252651887],
 ('grom', 6): [0.8333487318366937,
  1.2967712808002037,
  1.7927034602200997,
  2.948416252926167],
 ('grom', 7): [0.43639973021230666,
  0.6648901090224064,
  0.922748992497872,
  1.4741743345531173],
 ('grom', 8): [1.1009238772439203,
  1.7104131839580918,
  2.510727272827287,
  4.150952133687437],
 ('jeev', 0): [2.5499177103241943,
  3.776073846581167,
  5.19457143094591,
  8.12226842075063],
 ('jeev', 1): [2.4606443208341204,
  3.6195052428004773,
  5.068913524688117,
  7.890145860502099],
 ('jeev', 2): [2.3524522396694865,
  3.5728537238461318,
  4.953728139053196,
  7.660166157875981],
 ('jeev', 3): [1.0145026097200847,
  1.8548870480805526,
  2.9750814845572533,
  5.4811705292092885]}

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2021-03-22 16:57:21.547313. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [7]:
for monk in ['grom', 'jeev']:
    for k in bounds.keys():
        if k[0] == monk:
            assert np.allclose(np.array(bounds[k]), np.array(old_bounds[k]))
            print('Key %s ok '%str(k))

Key ('grom', 3) ok 
Key ('grom', 0) ok 
Key ('grom', 1) ok 
Key ('grom', 6) ok 
Key ('grom', 7) ok 
Key ('grom', 4) ok 
Key ('grom', 5) ok 
Key ('grom', 8) ok 
Key ('grom', 2) ok 
Key ('jeev', 2) ok 
Key ('jeev', 1) ok 
Key ('jeev', 3) ok 
Key ('jeev', 0) ok 


/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2021-03-22 16:58:25.222950. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)

