In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
cd ~/bmi_dynamics_code

/Users/preeyakhanna/bmi_dynamics_code


In [ ]:
import ssm
from online_analysis import generate_models, generate_models_utils, util_fcns
import analysis_config
from online_analysis import util_fcns

In [4]:
%matplotlib notebook

In [5]:
pdb

Automatic pdb calling has been turned ON


In [ ]:
for animal in ['jeev', 'grom']: 
    for i_d in range(analysis_config.data_params['%s_ndays'%animal] ): 
        
        ## Mean subtraction ### 
        ## Do states # 1 - 5 # 
        print('########################################')
        print('########################################')
        print('########################################')
        print('########### STARTING %s, %d ############'%(animal, i_d))
        print('########################################')
        print('########################################')
        
        generate_models.sweep_slds_params(animal, i_d, ver=1, mean_sub=True)

Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
199 (15, 7)
new trial offset 199, total trls in this blk 199


/Users/preeyakhanna/bmi_dynamics_code/online_analysis/generate_models_utils.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  tmp = np.array([np.zeros(( bin_spk[x].shape[0])) + ix + trl_off for ix, x in enumerate(ix_mod)])


Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
171 (46, 7)
Len Obs Targs [1 2 3 4 5 6 8 9]
REMOVING A TRIAL: Animal jeev, TargIx -1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
new trial offset 358, total trls in this blk 159


/Users/preeyakhanna/conda/envs/mountainlab/lib/python3.6/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Animal jeev, tsk 0, N = 2859
Tsk 0, Trg 0.00, N = 307
Tsk 0, Trg 1.00, N = 339
Tsk 0, Trg 2.00, N = 445
Tsk 0, Trg 3.00, N = 429
Tsk 0, Trg 4.00, N = 337
Tsk 0, Trg 5.00, N = 294
Tsk 0, Trg 6.00, N = 342
Tsk 0, Trg 7.00, N = 366
Animal jeev, tsk 1, N = 5181
Tsk 1, Trg 2.10, N = 624
Tsk 1, Trg 3.00, N = 573
Tsk 1, Trg 4.00, N = 1103
Tsk 1, Trg 5.10, N = 607
Tsk 1, Trg 6.00, N = 164
Tsk 1, Trg 6.10, N = 830
Tsk 1, Trg 8.00, N = 587
Tsk 1, Trg 9.10, N = 693
n spks in data 20
n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

Xlims: -0.05, 0.13
Ylims: 0.05, 0.23
Bin Curson kin Size 20
16 (38, 7)
new trial offset 16, total trls in this blk 16


/Users/preeyakhanna/bmi_dynamics_code/online_analysis/generate_models_utils.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  tmp = np.array([np.zeros(( bin_spk[x].shape[0])) + ix + trl_off for ix, x in enumerate(ix_mod)])


Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
152 (39, 7)
Len Obs Targs [1 2 3 4 5 6 8 9]
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
new trial offset 158, total trls in this blk 142


/Users/preeyakhanna/conda/envs/mountainlab/lib/python3.6/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Animal jeev, tsk 0, N = 460
Tsk 0, Trg 0.00, N = 118
Tsk 0, Trg 1.00, N = 39
Tsk 0, Trg 2.00, N = 81
Tsk 0, Trg 3.00, N = 61
Tsk 0, Trg 4.00, N = 20
Tsk 0, Trg 5.00, N = 33
Tsk 0, Trg 6.00, N = 68
Tsk 0, Trg 7.00, N = 40
Animal jeev, tsk 1, N = 4334
Tsk 1, Trg 2.10, N = 550
Tsk 1, Trg 3.00, N = 490
Tsk 1, Trg 4.00, N = 777
Tsk 1, Trg 5.10, N = 490
Tsk 1, Trg 6.00, N = 38
Tsk 1, Trg 6.10, N = 793
Tsk 1, Trg 8.00, N = 616
Tsk 1, Trg 9.10, N = 580
n spks in data 20
n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
90 (16, 7)
new trial offset 90, total trls in this blk 90


/Users/preeyakhanna/bmi_dynamics_code/online_analysis/generate_models_utils.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  tmp = np.array([np.zeros(( bin_spk[x].shape[0])) + ix + trl_off for ix, x in enumerate(ix_mod)])


Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
133 (35, 7)
Len Obs Targs [1 2 3 4 5 6 8 9]
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
new trial offset 218, total trls in this blk 128


/Users/preeyakhanna/conda/envs/mountainlab/lib/python3.6/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Animal jeev, tsk 0, N = 1382
Tsk 0, Trg 0.00, N = 151
Tsk 0, Trg 1.00, N = 152
Tsk 0, Trg 2.00, N = 172
Tsk 0, Trg 3.00, N = 243
Tsk 0, Trg 4.00, N = 160
Tsk 0, Trg 5.00, N = 201
Tsk 0, Trg 6.00, N = 171
Tsk 0, Trg 7.00, N = 132
Animal jeev, tsk 1, N = 3707
Tsk 1, Trg 2.10, N = 305
Tsk 1, Trg 3.00, N = 313
Tsk 1, Trg 4.00, N = 539
Tsk 1, Trg 5.10, N = 316
Tsk 1, Trg 6.00, N = 433
Tsk 1, Trg 6.10, N = 401
Tsk 1, Trg 8.00, N = 565
Tsk 1, Trg 9.10, N = 835
n spks in data 20
n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 20
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
80 (17, 7)
new trial offset 80, total trls in this blk 80


/Users/preeyakhanna/bmi_dynamics_code/online_analysis/generate_models_utils.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  tmp = np.array([np.zeros(( bin_spk[x].shape[0])) + ix + trl_off for ix, x in enumerate(ix_mod)])


Xlims: -0.08, 0.16
Ylims: 0.02, 0.26
Bin Curson kin Size 20
101 (46, 7)
Len Obs Targs [1 2 3 4 5 6 8 9]
REMOVING A TRIAL: Animal jeev, TargIx 1.0
Keeping JEEV target 2 2.7
Correcting JEEV target 2 -0.4
REMOVING A TRIAL: Animal jeev, TargIx 1.0
Correcting JEEV target 2 0.1
Correcting JEEV target 2 -0.1
REMOVING A TRIAL: Animal jeev, TargIx 1.0
Correcting JEEV target 2 -0.9
Correcting JEEV target 2 -0.0
Correcting JEEV target 2 -0.6
Correcting JEEV target 2 -0.3
REMOVING A TRIAL: Animal jeev, TargIx 1.0
REMOVING A TRIAL: Animal jeev, TargIx 1.0
Correcting JEEV target 2 -0.2
new trial offset 176, total trls in this blk 96


/Users/preeyakhanna/conda/envs/mountainlab/lib/python3.6/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Animal jeev, tsk 0, N = 1532
Tsk 0, Trg 0.00, N = 221
Tsk 0, Trg 1.00, N = 171
Tsk 0, Trg 2.00, N = 154
Tsk 0, Trg 3.00, N = 171
Tsk 0, Trg 4.00, N = 182
Tsk 0, Trg 5.00, N = 200
Tsk 0, Trg 6.00, N = 221
Tsk 0, Trg 7.00, N = 212
Animal jeev, tsk 1, N = 4131
Tsk 1, Trg 2.00, N = 52
Tsk 1, Trg 2.10, N = 352
Tsk 1, Trg 3.00, N = 205
Tsk 1, Trg 4.00, N = 499
Tsk 1, Trg 5.10, N = 201
Tsk 1, Trg 6.00, N = 1119
Tsk 1, Trg 6.10, N = 213
Tsk 1, Trg 8.00, N = 774
Tsk 1, Trg 9.10, N = 716
n spks in data 21
n spks in trls_train 21
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 21
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 21
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 21
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 21
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 64, total trls in this blk 64


/Users/preeyakhanna/bmi_dynamics_code/online_analysis/generate_models_utils.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  tmp = np.array([np.zeros(( bin_spk[x].shape[0])) + ix + trl_off for ix, x in enumerate(ix_mod)])


(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 165, total trls in this blk 101
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 287, total trls in this blk 122


/Users/preeyakhanna/conda/envs/mountainlab/lib/python3.6/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Animal grom, tsk 0, N = 2229
Tsk 0, Trg 0.00, N = 258
Tsk 0, Trg 1.00, N = 337
Tsk 0, Trg 2.00, N = 319
Tsk 0, Trg 3.00, N = 321
Tsk 0, Trg 4.00, N = 308
Tsk 0, Trg 5.00, N = 271
Tsk 0, Trg 6.00, N = 189
Tsk 0, Trg 7.00, N = 226
Animal grom, tsk 1, N = 9168
Tsk 1, Trg 0.10, N = 1028
Tsk 1, Trg 1.10, N = 1067
Tsk 1, Trg 2.10, N = 1241
Tsk 1, Trg 3.10, N = 1471
Tsk 1, Trg 4.00, N = 550
Tsk 1, Trg 4.10, N = 1286
Tsk 1, Trg 5.00, N = 992
Tsk 1, Trg 6.10, N = 699
Tsk 1, Trg 7.10, N = 834
n spks in data 44
n spks in trls_train 44
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 44
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 44
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

n spks in trls_train 44
training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

training model ver 1


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

In [ ]:
##############################
##### FIGURE PLOTTING ########
##############################

fig, ax = plt.subplots(ncols = 2, figsize=(10, 4))
pkl_kw = dict(encoding='latin1')
mag_boundaries = pickle.load(open(analysis_config.data_params['mag_bound_file'], 'rb'), **pkl_kw)

for ia, animal in enumerate(['grom', 'jeev']):
    
    #### tuning models ########
    fname = analysis_config.config[animal+'_pref']+'tuning_models_%s_model_set6_.pkl'%animal
    dat_ridge = pickle.load(open(fname, 'rb'), **pkl_kw)

    #### predict forward #######
    R2_pred_next_spks = []
    R2_pred_next_command = []
    
    #### ndays ######
    ndays = analysis_config.data_params['%s_ndays'%animal] 
    
    
    for day_ix in ndays:  
        
        #### spks true #####
        spks      = dat_ridge[day_ix, 'spks']

        ### ridge spks #####
        pred_spks = dat_ridge[day_ix, 'hist_1pos_0psh_0spksm_1_spksp_0'] ## no conditioning 
        
        ### Quick comparison for now ### 
        neural_push = dat_ridge[day_ix, 'np']

        command_bins = util_fcns.commands2bins([neural_push], mag_boundaries, animal, day_ix, 
                                           vel_ix=[0, 1])[0]
        
        ### Get these out for SLDS data comparison ### 
        bin_num = dat_ridge[day_ix, 'bin_num']
        trl = dat_ridge[day_ix, 'trl']
        
        ### load the SLDS data ### 
        with open('slds_sweep_%s_%d_1_mean_sub.pkl'%(animal, day_ix), 'rb') as f: 
            slds_dat_mean_sub = pickle.load(f)
        

        ### get SLDS data ### _ms
        pred1_ms, true1, trl1, bin_num1 = compile_slds_data(slds_dat_mean_sub, 1, 10)
        pred2_ms, true2, trl2, bin_num2 = compile_slds_data(slds_dat_mean_sub, 2, 10)
        pred3_ms, true3, trl3, bin_num3 = compile_slds_data(slds_dat_mean_sub, 3, 10)
        pred4_ms, true4, trl4, bin_num4 = compile_slds_data(slds_dat_mean_sub, 4, 10)\
        pred5_ms, true5, trl5, bin_num5 = compile_slds_data(slds_dat_mean_sub, 5, 10)
        
        assert(np.all(trl1 == trl2))
        assert(np.all(trl1 == trl3))
        assert(np.all(trl1 == trl4))
        assert(np.all(trl1 == trl5))
        
        assert(np.all(bin_num1 == bin_num2))
        assert(np.all(bin_num1 == bin_num3))
        assert(np.all(bin_num1 == bin_num4))
        assert(np.all(bin_num1 == bin_num5))
        
        ### Check that these match up ### 
        valid_ix = []; slds_ix = []; 
        
        for tmp, (tr, bn) in enumerate(zip(trl1, bin_num1)): 
            ix_tmp = np.nonzero(np.logical_and(trl == tr, bin_num == bn))[0]
            
            assert(len(ix_tmp) == 1)
            assert(np.all(true1[tmp, :] == true2[tmp, :]))
            assert(np.all(true1[tmp, :] == true3[tmp, :]))
            assert(np.all(true1[tmp, :] == true4[tmp, :]))
            assert(np.all(true1[tmp, :] == true5[tmp, :]))
            assert(np.all(true1[tmp, :] == spks[ix_tmp, :]))
            
            valid_ix.append(ix_tmp)
            slds_ix.append(tmp) 
            
        valid_ix = np.hstack((valid_ix)); 
        slds_ix = np.hstack((slds_ix))
        
        ### Magnitude less than 4 ###
        valid_ix_lte4 = np.nonzero(command_bins[valid_ix, 0] < 4)[0]
        
        ## index acceptable indices ### 
        valid_ix = valid_ix[valid_ix_lte4]
        slds_ix = slds_ix[valid_ix_lte4]
                
        ### Get R2 for predicting next spkes ### 
        r2_spks = util_fcns.get_R2(spks[valid_ix, :], pred_spks[valid_ix, :])
        
        r2_slds1_ms = util_fcns.get_R2(spks[valid_ix, :], pred1_ms[slds_ix, :])
        r2_slds2_ms = util_fcns.get_R2(spks[valid_ix, :], pred2_ms[slds_ix, :])
        r2_slds3_ms = util_fcns.get_R2(spks[valid_ix, :], pred3_ms[slds_ix, :])
        r2_slds4_ms = util_fcns.get_R2(spks[valid_ix, :], pred4_ms[slds_ix, :])
        r2_slds5_ms = util_fcns.get_R2(spks[valid_ix, :], pred5_ms[slds_ix, :])
        
        R2_pred_next_spks.append([r2_spks, r2_slds1_ms, r2_slds2_ms, r2_slds3_ms, r2_slds4_ms, r2_slds5_ms])
        
        ### Get R2 for predicting next command ### 
        KG = util_fcns.get_decoder(animal, day_ix)
        r2_spks = util_fcns.get_R2(np.dot(spks[valid_ix, :], KG.T), np.dot(pred_spks[valid_ix, :],
                                                                                   KG.T))
        
        r2_slds1_ms_kg = util_fcns.get_R2(np.dot(spks[valid_ix, :], KG.T), np.dot(pred1_ms[slds_ix, :],
                                                                                     KG.T))
        r2_slds2_ms_kg = util_fcns.get_R2(np.dot(spks[valid_ix, :], KG.T), np.dot(pred2_ms[slds_ix, :],
                                                                                     KG.T))
        r2_slds3_ms_kg = util_fcns.get_R2(np.dot(spks[valid_ix, :], KG.T), np.dot(pred3_ms[slds_ix, :],
                                                                                     KG.T))
        r2_slds4_ms_kg = util_fcns.get_R2(np.dot(spks[valid_ix, :], KG.T), np.dot(pred4_ms[slds_ix, :],
                                                                                     KG.T))
        r2_slds5_ms_kg = util_fcns.get_R2(np.dot(spks[valid_ix, :], KG.T), np.dot(pred5_ms[slds_ix, :],
                                                                                     KG.T))
        
        
        R2_pred_next_command.append([r2_spks, 
                                     r2_slds1_ms_kg, r2_slds2_ms_kg, r2_slds3_ms_kg, 
                                     r2_slds4_ms_kg, r2_slds5_ms_kg])
        
        
    offs = 8
    for ir2i, (R2, r2_lab) in enumerate(zip([R2_pred_next_spks, R2_pred_next_command],
                                 ['R2 pred spks', 'R2 pred com'])):   
        R2 = np.vstack((R2))
        
        for ir2_ in range(len(R2.shape[1])): 
            if ir2_ == 0: 
                if ir2i == 0: 
                    ax[ir2i].bar(ir2_, np.mean(R2[:, ir2_]), color = 'cyan')
                else: 
                    ax[ir2i].bar(ir2_, np.mean(R2[:, ir2_]), color = 'orange')
            else: 
                ax[ir2i].bar(ir2_, np.mean(R2[:, ir2_]), color = 'gray', alpha=(1.-(1./9.*ir2_)))
            
        
        for i in range(R2.shape[0]): 
            r2_ = R2[i, :]
            x_ = np.arange(len(r2_))
            ax[ir2i].plot(x_+offs*ia, r2_, 'k-', linewidth=.5)
            
        ### labels 
        ax[ir2i].set_ylabel(r2_lab)
        ax[ir2i].set_xticks(np.hstack((x_, x_ + offs)))
        
        labs = ['Rdg', 'rSLDS1', 'rSLDS2', 'rSLDS3', 'rSLDS4', 'rSLDS5']
        labs_all = []
        
        for L in ['G\n', 'J\n']: 
            labs_all.extend([L+l for l in labs])
            
        ax[ir2i].set_xticklabels(labs_all, 
                                 fontsize=8, rotation = 20) 

In [ ]:
def compile_slds_data(dat, k, niterfit=50): 
    pred = [];  
    true = [];
    trl = []; 
    bin_num = []; 

    for i in range(5): 
        pred_spks = np.vstack(( dat['save_params_post'][(i, k, niterfit, 0.01, 5, 5, 'pred_spks')] ))
        true_spks = np.vstack(( dat['save_params_post'][(i, k, niterfit, 0.01, 5, 5, 'true_spks')] )) 

        ### Params ### 
        params    = np.vstack(( dat['save_params_post'][(i, k, niterfit, 0.01, 5, 5, 'pred_spks_params')] )) 

        pred.append(pred_spks)
        true.append(true_spks)
        trl.append(params[:, 0])
        bin_num.append(params[:, 1])

    ## vstack ## 
    pred = np.vstack((pred))
    true = np.vstack((true))
    trl = np.hstack((trl))
    bin_num = np.hstack((bin_num))

    return pred, true, trl, bin_num