In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from online_analysis import generate_models

in task
in task
in task
Import Error in db.namelist: from tasklist import tasks -- likely error in a single task preventing import
error importing BMI configuration variables


Traceback (most recent call last):
  File "/Users/preeyakhanna/bmi3d/db/namelist.py", line 92, in <module>
    from bmilist import *
  File "/Users/preeyakhanna/bmi3d/config_files/bmilist.py", line 25, in <module>
    from ismore.ismore_bmi_lib import StateSpaceArmAssist, StateSpaceReHand, StateSpaceIsMore
ImportError: No module named ismore.ismore_bmi_lib
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pybasicbayes-0.2.4-py2.7-macosx-10.9-x86_64.egg/pybasicbayes/util/stats.py:11: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-11-10 15:09:49.287545. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [26]:
generate_models.model_ind_cell_tuning_SHUFFLE(nshuffs=2, shuff_type = 'mn_diff_maint')

online_analysis/generate_models_utils.py:111: DeprecationWarning: openFile() is pending deprecation, use open_file() instead. You may use the pt2to3 tool to update your source code.
  hdf = tables.openFile(pref+hdf[hdfix:])



##############################
########## DAY 0 ##########
##############################
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(64,) (64,) (18, 44) 6 (18,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 64, total trls in this blk 64
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(101,) (101,) (40, 44) 6 (40,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 165, total trls in this blk 101
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
(122,) (122,) (97, 44) 6 (97,)
[0. 1. 2. 3. 4. 5. 6. 7.]
new trial offset 287, total trls in this blk 122


KeyboardInterrupt: 

> /Users/preeyakhanna/bmi_dynamics_code/online_analysis/generate_models_utils.py(1336)within_bin_shuffling_mean_main()
   1335                             ix_keep.append(mov2_ix)
-> 1336                             cnt += len(mov2_ix)
   1337 

ipdb> c


/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-11-10 19:34:17.907035. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)



In [20]:
pdb

Automatic pdb calling has been turned ON


/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2020-11-10 19:14:25.231531. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)

