In [1]:
c

/Users/preeyakhanna


In [3]:
cd ~/bmi_dynamics_code/

/Users/preeyakhanna/bmi_dynamics_code


In [5]:
from online_analysis import util_fcns

In [6]:
import analysis_config

In [8]:
kgs = pickle.load(open(analysis_config.config['jeev_pref']+'jeev_KG_approx_fit.pkl', 'rb'))#, **pkl_kw)

In [23]:
kgs[1, 'F']

matrix([[ 1.        ,  0.        ,  0.        ,  0.1       ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
          0.1       ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.81204671,  0.        ,
         -0.25593384,  0.01818364],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.10261021,  0.        ,
          0.70946317, -0.44643031],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  1.        ]])

In [42]:
for i in [0, 1, 2,  6, 7, 8]:  
    F, K = util_fcns.get_grom_decoder(i)
    assert(np.allclose(F[0, 0], 1.))
    assert(np.allclose(F[0, 2],  0.))
    assert(np.allclose(F[0, 3],  .07))
    assert(np.allclose(F[0, 5],  0))
    assert(np.allclose(F[2, 0],  0.))
    assert(np.allclose(F[2, 2],  1.))
    assert(np.allclose(F[2, 3],  .0))
    assert(np.allclose(F[2, 5],  0.07))
    assert(np.allclose(F[3, 0], 0.))
    assert(np.allclose(F[3, 2], 0.))
    assert(np.allclose(F[3, 3], .5))
    assert(np.allclose(F[3, 5], 0.0))
    
    assert(np.allclose(F[5, 0], 0.))
    assert(np.allclose(F[5, 2], 0.))
    assert(np.allclose(F[5, 3], 0.))
    assert(np.allclose(F[5, 5], 0.5))

AssertionError: 

In [43]:
F

array([[1.        , 0.        , 0.        , 0.08250575, 0.        ,
        0.00158026, 0.0672536 ],
       [0.        , 1.        , 0.        , 0.        , 0.1       ,
        0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.00158026, 0.        ,
        0.08635778, 0.07439351],
       [0.        , 0.        , 0.        , 0.73749616, 0.        ,
        0.00745106, 0.22952539],
       [0.        , 0.        , 0.        , 0.        , 0.8       ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00745106, 0.        ,
        0.75565877, 0.23165576],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        ]])

In [37]:
F

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         9.17946008e-02,  0.00000000e+00,  3.38568158e-04,
        -4.95124739e-02],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e-01,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         3.38568158e-04,  0.00000000e+00,  9.22837016e-02,
         6.34271371e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.76356361e-01,  0.00000000e+00,  1.11817072e-03,
        -1.43805297e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.00000000e-01,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.11817072e-03,  0.00000000e+00,  7.77971688e-01,
         1.81935457e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.0000000

In [20]:
plt.imshow(F)
plt.colorbar()

In [25]:
F

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.00000000e-02,  0.00000000e+00,  0.00000000e+00,
        -5.79660402e-02],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.00000000e-02,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.47124093e-19,  0.00000000e+00,  7.00000000e-02,
        -1.29652518e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.00000000e-01,  0.00000000e+00,  0.00000000e+00,
        -5.79660402e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.00000000e-01,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.23562046e-17,  0.00000000e+00,  5.00000000e-01,
        -1.29652518e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.0000000

In [23]:
F

array([[ 1.        ,  0.        ,  0.        ,  0.07      ,  0.        ,
         0.        , -0.05736084],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.07      ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.07      , -0.06333065],
       [ 0.        ,  0.        ,  0.        ,  0.5       ,  0.        ,
         0.        , -0.57360836],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.5       ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5       , -0.63330647],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ]])

In [10]:
%matplotlib notebook

In [12]:
pwd

u'/Users/preeyakhanna/bmi_dynamics_code'

In [13]:
cd ../Dropbox/TimeMachineBackups/grom2016/

/Users/preeyakhanna/Dropbox/TimeMachineBackups/grom2016


In [14]:
ls


LDS_maxL_ndims.pkl
LDS_maxL_ndims_lowD.pkl
LDSmodels_nstates_15_separate_models_w_dyn_inno_norms.pkl
LDSmodels_nstates_20_combined_models.pkl
LDSmodels_nstates_20_separate_models.pkl
LDSmodels_nstates_20_separate_models_w_dyn_inno_norms.pkl
ZSC_values_7_16_18.pkl
backup_4_2022_tuning_models_grom_model_set11_task_spec_pls_gen.pkl
backup_7_2022_tuning_models_grom_model_set11_task_spec_pls_gen.pkl
co_decoder.pkl
co_obs_file_dict.pkl
co_obs_neuron_importance_dict.pkl
fig4_su_pop_mn_cm_stats.pkl
for_v.pkl
grom20160302_02_RMLC03021529.pkl
grom20160302_04_te4377.hdf
grom20160302_05_te4378.hdf
grom20160302_09_te4382.hdf
grom20160302_11_te4384.hdf
grom20160304_05_RMLC03041439.pkl
grom20160304_07_te4391.hdf
grom20160304_08_RMLC03041459.pkl
grom20160304_08_te4392.hdf
grom20160304_10_te4394.hdf
grom20160304_11_te4395.hdf
grom20160304_12_te4396.hdf
grom20160307_02_RMLC03071555.pkl
grom20160307_04_te4411.hdf
grom20160307_05_te4412.hdf
grom20160307_08_te4415.hdf
grom20160315_07_kf_rml_noivc03151619.p

In [15]:
x = pickle.load(open('grom20160304_05_RMLC03041439.pkl', 'rb'))

In [16]:
x

In [19]:
# Use X/Z indices
tmp = np.array([0, 2, 3, 5, 6])
x.filt.A[np.ix_(tmp, tmp)]

matrix([[1. , 0. , 0.1, 0. , 0. ],
        [0. , 1. , 0. , 0.1, 0. ],
        [0. , 0. , 0.8, 0. , 0. ],
        [0. , 0. , 0. , 0.8, 0. ],
        [0. , 0. , 0. , 0. , 1. ]])